### ISSUE TITLE
Host the documentation somewhere

### ISSUE THREAD

**Issue by thofma** [mathehertogh/adeles#1]
Would it be possible to host the documentation somewhere? For example on github by pushing it to the `gh-pages` branch? Would be nice if one could look at the documentation without cloning it.

Or maybe it is hosted somewhere and I did not find the link?

**Comment by mathehertogh** [comment]
Hi Tommy,

The documentation is online! I did not update the README file yet, I will do this.
You can find the documentation here:
https://mathehertogh.github.io/adeles/

I'm happy to hear any comments!

Kind regards,
Mathé

**Comment by thofma** [comment]
Great, thanks!

P.S.: Nice package.
